
spring:
    datasource:
        url: "jdbc:mysql://localhost/sdjeans"
        
        username: root
        password: password
        #これにより.sqlがspring bootを再起動するたびに実行できるようになる　
    # sql:
    #     init:
    #         mode: always
    #         encoding: UTF-8

    # mail
    mail:
        host: aspmx.l.google.com
        port: 25

logging:
    level:
        root : info
    file:
        name : app.log
    logback:
        rollingpolicy:
            max-file-size : 1MB
mybatis:
    configuration:
        map-underscore-to-camel-case: true

server:
  port: 8443
  ssl:
    key-store: classpath:localhost.p12
    key-store-type: PKCS12
    key-store-password: changeit
